import AccountOpening from "../services/api/resources/account-opening";
import ApiGateway from "../services/api/resources/api-gateway";
import Audit from "../services/api/resources/audit";
import BankMonitoring from "../services/api/resources/bank-monitoring";
import Catalog from "../services/api/resources/catalog";
import CRMService from "../services/api/resources/crm";
import Liquidity from "../services/api/resources/liquidity";
import Messaging from "../services/api/resources/messaging";
import Nip from "../services/api/resources/nip";
import Onboarding from "../services/api/resources/onboarding";
import Passport from "../services/api/resources/passport";
import Platform from "../services/api/resources/platform";
import Quickteller from "../services/api/resources/quickteller";
import Settlement from "../services/api/resources/settlement";
import Transaction from "../services/api/resources/transaction";
import TransactionHistory from "../services/api/resources/transaction-history";
import TransactionV1 from "../services/api/resources/transaction-v1";
import TransactionV3 from "../services/api/resources/transaction-v3";
import UserManagement from "../services/api/resources/user-management";
export const accountOpeningService = new AccountOpening();
export const apiGatewayService = new ApiGateway();
export const auditService = new Audit();
export const liquidityService = new Liquidity();
export const messagingService = new Messaging();
export const nipService = new Nip();
export const onboardingService = new Onboarding();
export const passportService = new Passport();
export const platformService = new Platform();
export const quicktellerService = new Quickteller();
export const catalogService = new Catalog();
export const settlementService = new Settlement();
export const transactionHistoryService = new TransactionHistory();
export const transactionService = new Transaction();
export const transactionServiceV3 = new TransactionV3();
export const userManagementService = new UserManagement();
export const transactionServiceV1 = new TransactionV1();
export const bankMonitoringService = new BankMonitoring();
export const crmService = new CRMService();
