export const REPLACE_CART = 'REPLACE_CART';
export const REPLACE_DISABLED_PRIMARY_CHOICES = (
  'REPLACE_DISABLED_PRIMARY_CHOICES'
);
export const SET_INITIATE_RESPONSE = 'SET_INITIATE_RESPONSE';
export const SET_PROCEED_RESPONSE = 'SET_PROCEED_RESPONSE';
export const SET_SELECTED_SUB_OPTION = 'SET_SELECTED_SUB_OPTION';
export const SET_SUB_OPTION_DATA = 'SET_SUB_OPTION_DATA';
export const SET_SUB_OPTIONS_NAME = 'SET_SUB_OPTIONS_NAME';
export const SET_SUB_OPTIONS = 'SET_SUB_OPTIONS';
